export default {
  login: "Mohit-Rakh",
  id: 42133389,
  node_id: "MDQ6VXNlcjQyMTMzMzg5",
  avatar_url:
    "https://pbs.twimg.com/media/E0i4JnIXsAAiIyQ?format=jpg&name=large",
  // "https://i.pinimg.com/474x/d9/21/4a/d9214ad661353dffe8846da342e1a004.jpg",
  gravatar_id: "",
  url: "https://api.github.com/users/mohitrakh",
  html_url: "https://github.com/mohitrakh",
  followers_url: "https://api.github.com/users/mohitrakh/followers",
  following_url:
    "https://api.github.com/users/mohitrakh/following{/other_user}",
  gists_url: "https://api.github.com/users/mohitrakh/gists{/gist_id}",
  starred_url: "https://api.github.com/users/mohitrakh/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/mohitrakh/subscriptions",
  organizations_url: "https://api.github.com/users/mohitrakh/orgs",
  repos_url: "https://api.github.com/users/mohitrakh/repos",
  events_url: "https://api.github.com/users/mohitrakh/events{/privacy}",
  received_events_url: "https://api.github.com/users/mohitrakh/received_events",
  type: "User",
  site_admin: false,
  name: "Mohit Rakh",
  company: "React Developer",
  blog: "www.google.com",
  location: "Gujrat",
  email: null,
  hireable: null,
  bio: "This is dummy user you can start searching",
  twitter_username: "mohit_rakh",
  public_repos: 52,
  public_gists: 0,
  followers: 495,
  following: 2034,
  created_at: "2018-08-06T06:48:23Z",
  updated_at: "2020-07-08T05:01:32Z",
};
